#include "algorithm.h"

#ifndef PROTOSHARES_MINER_H
#define PROTOSHARES_MINER_H

#define OLDVERSION 1

#define MAX_MOMENTUM_NONCE		0x4000000
#define BIRTHDAYS_PER_HASH		8

#undef CACHED_HASHES 
#undef COLLISION_TABLE_BITS
#undef COLLISION_TABLE_SIZE
#undef COLLISION_KEY_WIDTH
#undef COLLISION_KEY_MASK
#define COLLISION_TABLE_BITS	(27)
#define COLLISION_TABLE_SIZE	0x8000000 // (1<<COLLISION_TABLE_BITS)
#define COLLISION_KEY_WIDTH		5
#define COLLISION_KEY_MASK		0xF8000000 //(0xFFFFFFFF<<(COLLISION_TABLE_BITS))

#endif //PROTOSHARES_MINER_H
